#!/sbin/busybox sh

if [ "a$2" != "a" ];then

filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd

if [ "$eq_selection" == "0" ];
then

case "$eq_preset" in
  0)
    echo 0 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  1)
    echo 0 > /sys/class/misc/wolfson_control/switch_eq_headphone

    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 12 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 8 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 3 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo -1 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 1 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  2)
    echo 0 > /sys/class/misc/wolfson_control/switch_eq_headphone

    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 10 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 7 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 2 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 5 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  3)
    echo 0 > /sys/class/misc/wolfson_control/switch_eq_headphone

    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo -5 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 1 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 4 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 3 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  4)
    echo 0 > /sys/class/misc/wolfson_control/switch_eq_headphone

    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo -3 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo -5 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  5)
    echo 0 > /sys/class/misc/wolfson_control/switch_eq_headphone

    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 8 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 3 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo -2 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 3 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 8 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  6)
    echo 0 > /sys/class/misc/wolfson_control/switch_eq_headphone

    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 12 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 8 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 4 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 2 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 3 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  7)
    echo 0 > /sys/class/misc/wolfson_control/switch_eq_headphone

    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 10 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 2 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo -1 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 2 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 10 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
esac;
else
    echo 0 > /sys/class/misc/wolfson_control/switch_eq_headphone

    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo $eq_hp_gain_1 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo $eq_hp_gain_2 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo $eq_hp_gain_3 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo $eq_hp_gain_4 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo $eq_hp_gain_5 > /sys/class/misc/wolfson_control/eq_hp_gain_5
fi

fi
fi
