#!/sbin/busybox sh

if [ "a$2" != "a" ];then

filename=$(basename $2)

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd
else
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$$filename"'
  eval $evalcmd

#echo -${digital_gain}000 > /sys/class/misc/scoobydoo_sound/digital_gain
#echo 1 A 0x0FBB > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
#echo 1 B 0x0407 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
#echo 1 PG 0x0114 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
#echo 2 A 0x1F8C > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
#echo 2 B 0xF073 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
#echo 2 C 0x040A > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values
#echo 2 PG 0x01C8 > /sys/class/misc/scoobydoo_sound/headphone_eq_bands_values

if [ "$eq_selection" == "0" ];
then
case "$eq_preset" in
  0)
    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  1)
    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 12 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 8 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 3 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo -1 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 1 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  2)
    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 10 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 7 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 2 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 5 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  3)
    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo -5 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 1 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 4 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 3 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  4)
    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 0 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo -3 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo -5 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  5)
    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 8 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 3 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo -2 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 3 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 8 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  6)
    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 12 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 8 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo 4 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 2 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 3 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
  7)
    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo 10 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo 2 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo -1 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo 2 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo 10 > /sys/class/misc/wolfson_control/eq_hp_gain_5
    ;;
esac;
else
    echo 1 > /sys/class/misc/wolfson_control/switch_eq_headphone
    echo $eq_hp_gain_1 > /sys/class/misc/wolfson_control/eq_hp_gain_1
    echo $eq_hp_gain_2 > /sys/class/misc/wolfson_control/eq_hp_gain_2
    echo $eq_hp_gain_3 > /sys/class/misc/wolfson_control/eq_hp_gain_3
    echo $eq_hp_gain_4 > /sys/class/misc/wolfson_control/eq_hp_gain_4
    echo $eq_hp_gain_5 > /sys/class/misc/wolfson_control/eq_hp_gain_5
fi

fi
fi
