#!/sbin/busybox sh

if [ "$zram_switch" == "on" ];then

  swapoff /dev/block/zram0 > /dev/null 2>&1
  swapoff /dev/block/zram1 > /dev/null 2>&1
  swapoff /dev/block/zram2 > /dev/null 2>&1
  swapoff /dev/block/zram3 > /dev/null 2>&1
  echo 1 > /sys/devices/virtual/block/zram0/reset & pid1=$!
  echo 1 > /sys/devices/virtual/block/zram1/reset & pid2=$!
  echo 1 > /sys/devices/virtual/block/zram2/reset & pid3=$!
  echo 1 > /sys/devices/virtual/block/zram3/reset & pid4=$!
  LOOP=0
  FINISH=0
  # Assume we have maximum of 180 seconds, just in case we got infinite loop
  while [ $LOOP -lt 90 ] && [ $FINISH -ne 1 ] ; do
    if [ `ps | awk '{print $2}' | grep $pid1 | wc -l` -eq 0 ] && [ `ps | awk '{print $2}' | grep $pid2 | wc -l` -eq 0 ] && [ `ps | awk '{print $2}' | grep $pid3 | wc -l` -eq 0 ] && [ `ps | awk '{print $2}' | grep $pid4 | wc -l` -eq 0 ]; then
      # All exited, so it's over
      FINISH=1
    fi
    LOOP=`expr $LOOP + 1`
    sleep 2
  done
  
 case "$zram_disks" in
 1)
  echo `expr $zram_size \* 1024 \* 1024` > /sys/devices/virtual/block/zram0/disksize
  echo `expr $zram_swappiness \* 1` > /proc/sys/vm/swappiness
  mkswap /dev/block/zram0 > /dev/null 2>&1
  /sbin/busybox2 swapon -p 2 /dev/block/zram0 > /dev/null 2>&1
 ;;
 2)
  echo `expr $zram_size \* 1024 \* 512` > /sys/devices/virtual/block/zram0/disksize
  echo `expr $zram_size \* 1024 \* 512` > /sys/devices/virtual/block/zram1/disksize
  echo `expr $zram_swappiness \* 1` > /proc/sys/vm/swappiness
  mkswap /dev/block/zram0 > /dev/null 2>&1
  /sbin/busybox2 swapon -p 2 /dev/block/zram0 > /dev/null 2>&1
  mkswap /dev/block/zram1 > /dev/null 2>&1
  /sbin/busybox2 swapon -p 2 /dev/block/zram1 > /dev/null 2>&1
 ;;
 4)
  echo `expr $zram_size \* 1024 \* 256` > /sys/devices/virtual/block/zram0/disksize
  echo `expr $zram_size \* 1024 \* 256` > /sys/devices/virtual/block/zram1/disksize
  echo `expr $zram_size \* 1024 \* 256` > /sys/devices/virtual/block/zram2/disksize
  echo `expr $zram_size \* 1024 \* 256` > /sys/devices/virtual/block/zram3/disksize
  echo `expr $zram_swappiness \* 1` > /proc/sys/vm/swappiness
  mkswap /dev/block/zram0 > /dev/null 2>&1
  /sbin/busybox2 swapon -p 2 /dev/block/zram0 > /dev/null 2>&1
  mkswap /dev/block/zram1 > /dev/null 2>&1
  /sbin/busybox2 swapon -p 2 /dev/block/zram1 > /dev/null 2>&1
  mkswap /dev/block/zram2 > /dev/null 2>&1
  /sbin/busybox2 swapon -p 2 /dev/block/zram2 > /dev/null 2>&1
  mkswap /dev/block/zram3 > /dev/null 2>&1
  /sbin/busybox2 swapon -p 2 /dev/block/zram3 > /dev/null 2>&1
 ;;
 esac;

fi


if [ "$zram_switch" == "off" ];then

  swapoff /dev/block/zram0 > /dev/null 2>&1
  swapoff /dev/block/zram1 > /dev/null 2>&1
  swapoff /dev/block/zram2 > /dev/null 2>&1
  swapoff /dev/block/zram3 > /dev/null 2>&1
  umount /dev/block/zram0 > /dev/null 2>&1
  umount /dev/block/zram1 > /dev/null 2>&1
  umount /dev/block/zram2 > /dev/null 2>&1
  umount /dev/block/zram3 > /dev/null 2>&1
	
fi


echo "Zram settings applied"
