#!/sbin/busybox sh

if [ "$zram_switch" == "on" ];then

  echo `expr $zram_swappiness \* 1` > /proc/sys/vm/swappiness
  swapoff /dev/block/zram0 > /dev/null 2>&1
  echo 1 > /sys/devices/virtual/block/zram0/reset
  echo `expr $zram_size \* 1024 \* 1024` > /sys/devices/virtual/block/zram0/disksize
  echo `expr $zram_swappiness \* 1` > /proc/sys/vm/swappiness
  mkswap /dev/block/zram0 > /dev/null 2>&1
  swapon /dev/block/zram0 > /dev/null 2>&1

fi


if [ "$zram_switch" == "off" ];then

	swapoff /dev/block/zram0 > /dev/null 2>&1
	umount /dev/block/zram0 > /dev/null 2>&1
	umount /dev/block/zram1 > /dev/null 2>&1
	
fi



